services:
  - type: web
    name: serbabisa
    env: docker
    plan: free
    region: singapore
    numInstances: 1
    # Disk dihapus agar benar-benar gratis tanpa perlu kartu kredit
    envVars:
      - key: PORT
        value: 5000
      - key: SERBABISA_DESKTOP
        value: "false"
